config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :softwares, only: [:index, :show]
  resources :social_handles, only: [:index, :show]
  resources :skills, only: [:index, :show]
  resources :projects, only: [:index, :show, :edit, :update]
  resources :contacts, only: [:index]
  post 'contacts/send_message'
  get 'home/about'
  root to: 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/social_handle.rb
class SocialHandle < ApplicationRecord
	validates :name, presence: true
	has_one_attached :image
end

app/controllers/social_handles_controller.rb
class SocialHandlesController < ApplicationController
  before_action :set_social_handle, only: %i[ show edit update destroy ]

  # GET /social_handles or /social_handles.json
  def index
    @social_handles = SocialHandle.all
  end

  # GET /social_handles/1 or /social_handles/1.json
  def show
  end

  # GET /social_handles/new
  def new
    @social_handle = SocialHandle.new
  end

  # GET /social_handles/1/edit
  def edit
  end

  # POST /social_handles or /social_handles.json
  def create
    @social_handle = SocialHandle.new(social_handle_params)

    respond_to do |format|
      if @social_handle.save
        format.html { redirect_to social_handle_url(@social_handle), notice: "Social handle was successfully created." }
        format.json { render :show, status: :created, location: @social_handle }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @social_handle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /social_handles/1 or /social_handles/1.json
  def update
    respond_to do |format|
      if @social_handle.update(social_handle_params)
        format.html { redirect_to social_handle_url(@social_handle), notice: "Social handle was successfully updated." }
        format.json { render :show, status: :ok, location: @social_handle }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @social_handle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /social_handles/1 or /social_handles/1.json
  def destroy
    @social_handle.destroy

    respond_to do |format|
      format.html { redirect_to social_handles_url, notice: "Social handle was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_social_handle
      @social_handle = SocialHandle.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def social_handle_params
      params.require(:social_handle).permit(:name, :about, :profile_url, :image)
    end
end

app/helpers/social_handles_helper.rb
module SocialHandlesHelper
end

app/views/social_handles/_form.html.erb
<%= form_with(model: social_handle) do |form| %>
  <% if social_handle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(social_handle.errors.count, "error") %> prohibited this social_handle from being saved:</h2>

      <ul>
        <% social_handle.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :about %>
    <%= form.text_area :about %>
  </div>

  <div class="field">
    <%= form.label :profile_url %>
    <%= form.text_field :profile_url %>
  </div>
  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/social_handles/edit.html.erb
<h1>Editing Social Handle</h1>

<%= render 'form', social_handle: @social_handle %>

<%= link_to 'Show', @social_handle %> |
<%= link_to 'Back', social_handles_path %>

app/views/social_handles/index.html.erb
<hr class="featurette-divider mx-5 text-light">
<div class="container-fluid">
  <div class="row text-center px-3 align-items-center">
    <div class="col-2 ">
      <%= link_to ('<i class="fa fa-arrow-left"></i>').html_safe, root_path, class:"mx-5 text-warning fs-1 align-items-start "%>
    </div>
    <div class="col-8">
      <h2 class="text-warning">SOCIAL HANDLES</h2>
    </div>
    <div class="col-2">
      <img src="<%=asset_path('social-media.png')%>" style= "width: 60px; height: 60px; border-radius: 20  %;" >
    </div>
  </div>
</div>
<hr class="featurette-divider mx-5 text-light">

<div class="container-fluid bg-dark rounded-3" style="width: 94%;">
  <div class="row text-center px-3 align-items-center d-flex justify-content-center shadow-lg">
    <div class="col-12 ">
      <h2 class="text-white my-4 fs-1">Feel Free To Connect With Me </h2>
      <hr class="featurette-divider mx-5 text-dark">
        <div class="container marketing mb-5">
          <div class="row text-center">
            <% @social_handles.each do |sh|%>
              <div class="col-lg-4 my-5">
                <%= image_tag(sh&.image_url, alt: "image",class:"bd-placeholder-img rounded-circle", style: "width: 180px; height: 180px;") %>
                <h2 class="text-warning"><%= sh.name %></h2>
                <p class="text-white"><%= truncate(strip_tags(sh.about),length: 120) %></p>
                <%= link_to "View Profile »", sh.profile_url_was, class: "btn bg-warning d-grid gap-2 d-md-block text-dark fs-4" %>
              </div><!-- /.col-lg-4 -->
            <%end%>
          </div>
        </div>
    </div>    
  </div>
</div>

<%#= link_to 'New Social Handle', new_social_handle_path %>

app/views/social_handles/new.html.erb
<h1>New Social Handle</h1>

<%= render 'form', social_handle: @social_handle %>

<%= link_to 'Back', social_handles_path %>

app/views/social_handles/show.html.erb
<div class="container-fluid my-3 shadow-lg" style="background-color: rgba(255,99,98,255);">
    <header class="d-flex justify-content-center py-3">
      <%= link_to ('<i class="fa fa-arrow-left"></i>').html_safe, social_handles_path, class:"mx-5 text-white fs-4 align-items-start "%>
    </header>
 </div>
<div class="container-fluid my-5 shadow-lg ">
  <div class="row text-center px-3 align-items-center d-flex justify-content-center">
    <div class="col-6 ">
      <h1>Centered hero</h1>
      <hr class="featurette-divider mx-5 text-dark">
      <p class="lead my-4">Quickly design and customize responsive mobile-first sites with Bootstrap, the world’s most popular front-end open source toolkit, featuring Sass variables and mixins, responsive grid system, extensive prebuilt components, and powerful JavaScript plugins.</p>
    </div>    
  </div>
</div>
<hr class="featurette-divider mx-5 my-5 text-dark">
<div class="container my-5">
    <div class="row p-4 pb-0 pe-lg-0 pt-lg-5 align-items-center rounded-3 border shadow-lg">
        <div class="col-lg-7 p-3 p-lg-5 pt-lg-3">
          <h1 class="display-4 fw-bold lh-1"><%= @social_handle.name %></h1>
          <p class="lead"><%= @social_handle.about %></p>
          <p class="lead"><%= @social_handle.profile_url %></p>
                  </div>
        <div class="col-lg-4 offset-lg-1 p-0 oprojectow-hidden ">
          <%= image_tag(@social_handle&.image_url, alt: "image",class:"bd-placeholder-img", style: "width: 50%;") %>
        </div>
    </div>
</div>  
<hr class="featurette-divider mx-5 my-5 text-dark">  