config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :softwares, only: [:index, :show]
  resources :social_handles, only: [:index, :show]
  resources :skills, only: [:index, :show]
  resources :projects, only: [:index, :show, :edit, :update]
  resources :contacts, only: [:index]
  post 'contacts/send_message'
  get 'home/about'
  root to: 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
  end

  def about
  end
  
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_experience_popup.html.erb
<!-- Button trigger modal -->
<button type="button" class= "btn col-lg-12 bg-warning" data-bs-toggle="modal" data-bs-target="#experienceModal">
  Read More »
</button>

<!-- Modal -->
<div class="modal fade" id="experienceModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg modal-dialog-centered ">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5 text-dark" id="exampleModalLabel">EXPERIENCE</h1>
        <button type="button" class="btn-close" style="background-color: white;" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn bg-warning col-lg-4" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/home/_personal_bio_popup.html.erb
<!-- Button trigger modal -->
<button type="button" class= "btn col-lg-12 bg-warning" data-bs-toggle="modal" data-bs-target="#exampleModal">
  Read More »
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg modal-dialog-centered ">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5 text-dark" id="exampleModalLabel">PERSONAL BIO</h1>
        <button type="button" class="btn-close" style="background-color: white;" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn bg-warning col-lg-4" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/home/_qualifications_popup.html.erb
<!-- Button trigger modal -->
<button type="button" class= "btn col-lg-12 bg-warning" data-bs-toggle="modal" data-bs-target="#qualitficationModal">
  Read More »
</button>

<!-- Modal -->
<div class="modal fade" id="qualitficationModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg modal-dialog-centered ">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5 text-dark" id="exampleModalLabel">QUALIFICATIONS</h1>
        <button type="button" class="btn-close" style="background-color: white;" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn bg-warning col-lg-4" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/home/about.html.erb
<hr class="featurette-divider mx-5 text-light">
<div class="container-fluid">
  <div class="row text-center px-3 align-items-center">
    <div class="col-2 ">
      <%= link_to ('<i class="fa fa-arrow-left"></i>').html_safe, root_path, class:"mx-5 text-warning fs-1 align-items-start "%>
    </div>
    <div class="col-8">
      <h2 class="text-warning">ABOUT ME</h2>
    </div>
    <div class="col-2">
      <img src="<%=asset_path('group.png')%>" style= "width: 60px; height: 60px; border-radius: 50%;" >
    </div>
  </div>
</div>
<hr class="featurette-divider mx-5 text-light">

<div class="container-fluid my-3 shadow-lg">
  <div class="row text-center align-items-center py-3">
    <div class="col-12 ">
      <h1 class="text-center text-light">|Software Developer|</h1>
     <hr class="featurette-divider mx-5 text-dark">
        <div class="container-fluid my-3 rounded-3 bg-dark" style="width: 97%;">
          <div class="row text-center px-3 align-items-center py-3">
            <div class="col-12 ">
              <h4 class="featurette-heading text-light fs-3 fw-bold my-3">Developer From Delhi, India!</h4>
              <hr class="featurette-divider mx-5 text-light">
                  <h5 class="lead fs-3 fst-italic my-5 text-warning">
                    Experienced software developer with a passion for developing innovative programs that
                    expedite the  efficiency and effectiveness of organizational success. Well-versed in
                    technology and writing code to create applications that are reliable and user-friendly.
                    Skilled leader who has the proven ability to motivate, educate, and manage a team of
                    professionals to build applications with quality. Confident communicator, strategic thinker,
                    and innovative creator to develop software that is customized to meet a company’s organizational
                    needs, and further their success.
                  </h5>
            </div>
          </div>
        </div>
      <hr class="featurette-divider mx-5 text-dark">
    </div>
  </div>
</div>

<div class="container-fluid d-flex justify-content-center my-5 text-center rounded-3 bg-dark" style="width: 95%;">
  <div class="row text-center align-items-center">
    <div class="col">
      <div class="card my-5 m-3 bg-white" style="width: 18rem;">
        <div class="card-body">
          <h5 class="card-title text-dark">Personal Bio!! </h5>
          <p class="card-text">My Name Is SOURAV RAJPUT a Web Developer From Delhi,India! Read More Click On View. </p>
          <%= render "home/personal_bio_popup"%>
          <%#= link_to "Read More »", home_about_path, class: "btn bg-warning d-grid gap-2 d-md-block" %>
        </div>
      </div>
    </div>
    <div class="col">
      <div class="card my-5 m-3 " style="width: 18rem;">
        <div class="card-body">
          <div class="card-body">
            <div class="card-body">
              <h5 class="card-title">Qualifications!!</h5>
              <p class="card-text">Here! You Can Check My Qualifications Read More Click On View.</p>
              <%= render "home/qualifications_popup"%>
              <%#= link_to "Read More »", home_about_path, class: "btn bg-warning d-grid gap-2 d-md-block text-dark"%>
            </div>  
          </div>
        </div>
      </div>
    </div>
    <div class="col">
      <div class="card my-5 m-3 bg-white" style="width: 18rem;">
        <div class="card-body">
          <h5 class="card-title text-dark">Experience!!</h5>
          <p class="card-text">Hey Buddy! You Can Check My Job Experience Read More Click On View. </p>
          <%= render "home/experience_popup"%>
          <%#= link_to "Connect Now »", social_handles_path, class: "btn bg-warning d-grid gap-2 d-md-block" %>
        </div>
      </div>
    </div>
  </div>
</div>


<div class="container-fluid rounded-3 bg-dark" style="width: 95%;">
  <div class="row text-center justify-content-center">
    <div class="col-11">
      <h1 class="mb-2 mt-3 text-warning">|More Things To Explore|</h1>
      <!-- <p class="mb-9 lead">
          Our focus is always on finding the best people to work with. Our bar is  <br>
                high, but you look ready to take on the challenge.
      </p> -->
      <hr class="featurette-divider mx-2 text-white">
        <div class="row mt-5">
          <div class="col-6">
            <div class="card bg-white" style="width: 100%;">
              <div class="card-body">
                <h5 class="card-title text-dark">Softwares I Use</h5>
                <p class="card-text text-dark">Software Is Most Important Thing To Develop Any Site 
                !Check The Softwares Which I Using Currently For Develop A Website</p>
                <%= link_to "View »", softwares_path, class: "btn bg-warning d-grid gap-2 d-md-block"%>
              </div>
            </div>
          </div>
          <div class="col-6">
            <div class="card" style="width: 100%; background-color: white;">
              <div class="card-body">
                <h5 class="card-title text-dark ">Socials Handles</h5>
                <p class="card-text text-dark pb-4 align-items-center">Feel Free To Connect With Me</p>
                <%= link_to "View »", social_handles_path, class: "btn bg-warning d-grid gap-2 d-md-block"%>
                <!-- <p>Our focus is always on finding the best people to work with. Our bar is  <br>
                high, but you look ready to take on the challenge.</p> -->
                <%#= link_to "View »", home_about_path, class: "btn btn-outline d-grid gap-2 d-md-block",style:"background-color: rgba(255,99,98,255);" %>
              </div>
            </div>
          </div>
          <div class="col-12 mt-1">
            <div class="card" style="width: 100%;">
              <div class="card-body">
                <h5 class="card-title text-dark mt-2">Success!    <span class="badge bg-success">New!</span></h5>
                <p class="card-text text-dark pb-4 py-3 align-items-center">Always Fight With Your Bad Time OR Fear, To Get Success! "The Greatest barrier To Success Is The Fear Of Failure."</p>
                
              </div>
            </div>
          </div>
      </div>

      <div class="row mt-1">
          <div class="col-6">
            <div class="card" style="width: 100%; background-color: white;">
              <div class="card-body">
                <h5 class="card-title text-dark">Coming Soon..</h5>
                <p class="card-text text-dar">Some Content Will Coming Soon About Me Stay Tuned!.</p>
                <%= link_to "Coming Soon.. »", home_about_path, class: "btn bg-warning d-grid gap-2 d-md-block"%>
              </div>
            </div>
          </div>
          <div class="col-6">
            <div class="card" style="width: 100%; background-color: white;">
              <div class="card-body">
                <h5 class="card-title text-dark">Coming Soon..</h5>
                <p class="card-text text-dar">Some Content Will Coming Soon About Me Stay Tuned!.</p>
                <%= link_to "Coming Soon.. »", home_about_path, class: "btn bg-warning d-grid gap-2 d-md-block"%>
              </div>
            </div>
          </div>
          <div class="col-12 mt-1 mb-4">
            <div class="card">
              <div class="card-body">
                <h5 class="card-title text-dark">Coming Soon..</h5>
                <p class="card-text">Some Content Will Coming Soon About Me Stay Tuned!.</p>
                <%= link_to "Coming Soon..»", home_about_path, class: "btn bg-warning d-grid gap-2 d-md-block"%>
              </div>
            </div>
          </div>
      </div>
      <hr class="featurette-divider mx-5 text-dark">
      <h5></h5>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<hr class="featurette-divider mx-5 text-light">
  <p class="fs-1 text-white text-center">Hii, I'M Sourav Rajput A Software Developer From Delhi, India!</p>
<hr class="featurette-divider mx-5 text-light">
<div class="container-fluid my-3 rounded-3 shadow-lg bg-dark" style="width: 100%;">
  <div class="row p-4 pb-0 pe-lg-0 pt-lg-5 align-items-center">
    <div class="col-lg-7">
      <h1 class="display-4 fw-bold lh-1 text-warning">Being A Software Developer</h1>
      <p class="lead text-white">(It's Amazing how much ground is constantly being broken in this field so constantly learning new concepts and technologies)</p>
      <p class="text-white">Once you replace negative thoughts with positive ones, you'll start having positive results</p>
      <div class="d-grid gap-2 d-md-flex justify-content-md-start mb-4 mb-lg-3">
        <%= link_to "EXPLORE MORE ",home_about_path, class:"btn col-lg-6 text-dark bg-warning fs-5"%>
      </div>
    </div>
    <div class="col-lg-4 offset-lg-1 p-0 overflow-hidden shadow-lg">
        <img src="<%=asset_path('logopic.jpg')%>" style= "width: 100%; height: 500px;">
    </div>
  </div>   
</div>

<div class="container-fluid my-4" style="width: 99%;">
  <div class="row">
    <div class="col-3">
      <p class="text-warning fs-5 fw-bold">1 Year Experience</p>
    </div>
    <div class="col-3">
      <p class="text-warning fs-5 fw-bold">3 Completed Projects</p>
    </div>
    <div class="col-3">
      <p class="text-warning fs-5 fw-bold">Hard Working</p>
    </div>
    <div class="col-3">
      <p class="text-warning fs-5 fw-bold">Dedicate To Work</p>
    </div>            
  </div>   
</div>  

<h2 class="text-warning">MORE ABOUT ME :</h2>
<div class="container-fluid my-2 rounded-3 bg-dark">
  <div class="row text-center p-4 pb-0 pe-lg-0 py-lg-3 align-items-center">
      <div class="container marketing my-3">
        <div class="row text-center">
          <div class="col-lg-4 my-5">
              <img src="<%= asset_path('group.png')%>" class="bd-placeholder-img ", style= "width: 180px; height: 180px;" >
            <h2 class="my-3 text-white">About Me</h2>
            <%= link_to "View »", home_about_path, class: "btn btn-outline text-dark fs-5 d-grid gap-2 d-md-block bg-warning"%>
          </div>
          <div class="col-lg-4 my-5">
              <img src="<%= asset_path('skill.png')%>" class="bd-placeholder-img ", style= "width: 180px; height: 180px;" >
            <h2 class="my-3 text-white">My Skills</h2>
            <%= link_to "View »", skills_path, class: "btn btn-outline text-dark fs-5 d-grid gap-2 d-md-block bg-warning"%>
          </div>
          <div class="col-lg-4 my-5">
              <img src="<%= asset_path('project.png')%>" class="bd-placeholder-img", style= "width: 180px; height: 180px;" >
            <h2 class="my-3 text-white">Projects</h2>
            <%= link_to "View »", projects_path, class: "btn btn-outline text-dark fs-5 d-grid gap-2 d-md-block bg-warning"%>
          </div> 
        </div>
      </div>
  </div>
</div>