config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :softwares, only: [:index, :show]
  resources :social_handles, only: [:index, :show]
  resources :skills, only: [:index, :show]
  resources :projects, only: [:index, :show, :edit, :update]
  resources :contacts, only: [:index]
  post 'contacts/send_message'
  get 'home/about'
  root to: 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/project.rb
class Project < ApplicationRecord
	validates :name, presence: true
	has_one_attached :image
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update ]

  def index
    @projects = Project.all
  end

  def new
    @project = Project.new
  end

  def create
    @project =Project.new(project_params)
    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end 
  end

  def show
    @projects = Project.all
  end

  def edit
  end

  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  private
   def set_project
    @project = Project.find(params[:id])
   end 

  def project_params
    params.require(:project).permit(:name, :about, :image, :project_url)
  end 
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_with(model: @project, url: projects_path, method: :post) do |form| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% @project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :about %>
    <%= form.text_area :about %>
  </div>
  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<div class="container-fluid my-5 border shadow-sm" style="background-color: rgba(255,99,98,255);">
  <div class="row text-center p-4 pb-0 pe-lg-0 py-lg-3 align-items-center border shadow-lg">
  	<div class="col-2">
  		<%= link_to ('<i class="fa fa-arrow-left"></i>').html_safe, projects_path, class:"mx-5 text-dark fs-2 align-items-start "%>	
  	</div>
  	<div class="col-8">
			<h2 class="text-center">Update project</h2>		
  	</div>
  </div>
</div> 

<div class="new-page-form">
		<%= form_with(model: @project, url: project_path, method: :put) do |form| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% @project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :about %>
    <%= form.text_area :about %>
  </div>
  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

</div>

app/views/projects/index.html.erb
<hr class="featurette-divider mx-5 text-light">
<div class="container-fluid">
  <div class="row text-center px-3 align-items-center">
    <div class="col-2 ">
      <%= link_to ('<i class="fa fa-arrow-left"></i>').html_safe, root_path, class:"mx-5 text-warning fs-1 align-items-start "%>
    </div>
    <div class="col-8">
      <h2 class="text-warning">PROJECTS</h2>
    </div>
    <div class="col-2">
      <img src="<%=asset_path('project.png')%>" style= "width: 60px; height: 60px; border-radius: 20  %;" >
    </div>
  </div>
</div>
<hr class="featurette-divider mx-5 text-light">

<div class="container-fluid  shadow-lg ">
  <div class="row text-center  align-items-center d-flex justify-content-center">
    <div class="col-6">
      <p class="lead text-white">If Your Actions Inspire Others To Dream More, Learn More, Do More And Become More, You Are A Leader.</p>
    </div>    
  </div>
</div>

<div class="container-fluid bg-dark rounded-3"  style="width: 95%;">
  <div class="row text-center px-3 align-items-center d-flex justify-content-center shadow-lg">
    <div class="col-12 ">
      <hr class="featurette-divider mx-5 text-dark">
        <div class="container marketing mb-5">
          <div class="row text-center">
            <% @projects.each do |project|%>
              <div class="col-lg-4 my-5">
                <%= image_tag(project&.image_url, alt: "image", class:"bd-placeholder-img ", style: "width: 250px; height: 180px;")%>
                <h2 class="my-3 text-warning"><%= project.name %></h2>
                <p class="text-white"><%= truncate(strip_tags(project.about),length: 120) %></p>
                <%= link_to "View »", project_path(project.id), class: "btn btn-outline d-grid gap-2 d-md-block text-dark bg-warning fs-4" %>
              </div>
            <%end%>
          </div>
        </div>
    </div>    
  </div>
</div>

app/views/projects/new.html.erb
<div class="container-fluid my-5 border shadow-sm" style="background-color: rgba(255,99,98,255);">
  <div class="row text-center p-4 pb-0 pe-lg-0 py-lg-3 align-items-center border shadow-lg">
  	<div class="col-2">
  		<%= link_to ('<i class="fa fa-arrow-left"></i>').html_safe, projects_path, class:"mx-5 text-dark fs-2 align-items-start "%>	
  	</div>
  	<div class="col-8">
			<h2 class="text-center">Add Projects</h2>		
  	</div>
  </div>
</div> 

<div class="new-page-form">
		<%= render 'form'%>
</div>

		

app/views/projects/show.html.erb
<hr class="featurette-divider mx-5 text-light">
<div class="container-fluid">
  <div class="row text-center px-3 align-items-center">
    <div class="col-12 ">
      <%= link_to ('<i class="fa fa-arrow-left"></i>').html_safe, projects_path, class:"mx-5 text-warning fs-1 align-items-start "%>
    </div>
  </div>
</div>
<hr class="featurette-divider mx-5 text-light">

<div class="container-fluid">
  <div class="row text-center px-3 align-items-center d-flex justify-content-center">
    <div class="col-8 ">
      <h1 class="text-warning">Centered hero</h1>
      <hr class="featurette-divider mx-5 text-dark">
      <p class="lead text-white">Quickly design and customize responsive mobile-first sites with Bootstrap, the world’s most popular front-end open source toolkit, featuring Sass variables and mixins, responsive grid system, extensive prebuilt components, and powerful JavaScript plugins.</p>
    </div>    
  </div>
</div>

<div class="container my-5 bg-dark">
    <div class="row p-4 pb-0 pe-lg-0 pt-lg-5 align-items-center rounded-3 border shadow-lg">
      	<div class="col-lg-7 p-3 p-lg-5 pt-lg-3">
        	<h1 class="display-4 fw-bold lh-1 text-warning"><%= @project.name %></h1>
       	 	<p class="lead text-white"><%= @project.about %></p>
      	</div>
      	<div class="col-lg-4 offset-lg-1 p-0 oprojectow-hidden ">
         		<%= image_tag @project&.image_url,alt: "image", class:"bd-placeholder-img", style: "width: 80%;" %>
      	</div>
    </div>
</div>  
<hr class="featurette-divider mx-5 my-5 text-dark">  