config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :softwares, only: [:index, :show]
  resources :social_handles, only: [:index, :show]
  resources :skills, only: [:index, :show]
  resources :projects, only: [:index, :show, :edit, :update]
  resources :contacts, only: [:index]
  post 'contacts/send_message'
  get 'home/about'
  root to: 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/software.rb
class Software < ApplicationRecord
	validates :name, presence: true
	has_one_attached :image
end

app/controllers/softwares_controller.rb
class SoftwaresController < ApplicationController
  before_action :set_software, only: %i[ show edit update destroy ]

  # GET /softwares or /softwares.json
  def index
    @softwares = Software.all
  end

  # GET /softwares/1 or /softwares/1.json
  def show
  end

  # GET /softwares/new
  def new
    @software = Software.new
  end

  # GET /softwares/1/edit
  def edit
  end

  # POST /softwares or /softwares.json
  def create
    @software = Software.new(software_params)

    respond_to do |format|
      if @software.save
        format.html { redirect_to software_url(@software), notice: "Software was successfully created." }
        format.json { render :show, status: :created, location: @software }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @software.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /softwares/1 or /softwares/1.json
  def update
    respond_to do |format|
      if @software.update(software_params)
        format.html { redirect_to software_url(@software), notice: "Software was successfully updated." }
        format.json { render :show, status: :ok, location: @software }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @software.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /softwares/1 or /softwares/1.json
  def destroy
    @software.destroy

    respond_to do |format|
      format.html { redirect_to softwares_url, notice: "Software was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_software
      @software = Software.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def software_params
      params.require(:software).permit(:name, :about, :image)
    end
end

app/helpers/softwares_helper.rb
module SoftwaresHelper
end

app/views/softwares/_form.html.erb
<%= form_with(model: software) do |form| %>
  <% if software.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(software.errors.count, "error") %> prohibited this software from being saved:</h2>

      <ul>
        <% software.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :about %>
    <%= form.text_area :about %>
  </div>
  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/softwares/edit.html.erb
<h1>Editing Software</h1>

<%= render 'form', software: @software %>

<%= link_to 'Show', @software %> |
<%= link_to 'Back', softwares_path %>

app/views/softwares/index.html.erb
<hr class="featurette-divider mx-5 text-light">
<div class="container-fluid">
  <div class="row text-center px-3 align-items-center">
    <div class="col-2 ">
      <%= link_to ('<i class="fa fa-arrow-left"></i>').html_safe, root_path, class:"mx-5 text-warning fs-1 align-items-start "%>
    </div>
    <div class="col-8">
      <h2 class="text-warning">SOFTWARES</h2>
    </div>
    <div class="col-2">
      <img src="<%=asset_path('software.png')%>" style= "width: 60px; height: 60px; border-radius: 50%;" >
    </div>
  </div>
</div>
<hr class="featurette-divider mx-5 text-light">


<div class="container-fluid my-5 bg-dark rounded-3" style="width: 95%;">
  <div class="row text-center px-3 align-items-center d-flex justify-content-center">
    <div class="col-8 text-white">
      <h1>Enjoy To Use These Softwares</h1>
      <hr class="featurette-divider mx-5 text-white">
      <p class="lead my-4">Quickly design and customize responsive mobile-first sites with Bootstrap, the world’s most popular front-end open source toolkit, featuring Sass variables and mixins, responsive grid system, extensive prebuilt components, and powerful JavaScript plugins.</p>
    </div>    
  </div>
</div>

<div class="container-fluid bg-dark rounded-3" style="width: 95%;">
  <div class="row text-center px-3 align-items-center d-flex justify-content-center shadow-lg">
    <div class="col-12 ">
      <hr class="featurette-divider mx-5 text-dark">
        <div class="container marketing mb-5">
          <div class="row text-center">
            <% @softwares.each do |sh|%>
              <div class="col-lg-4 my-2">
                <%= image_tag(sh&.image_url, alt: "image",class:"bd-placeholder-img rounded-circle", style: "width: 180px; height: 180px;") %>
                <h2 class="text-warning my-3"><%= sh.name %></h2>
                <p class="text-white"><%= truncate(strip_tags(sh.about),length: 120) %></p>
                <%= link_to "View »", software_path(sh.id), class: "btn bg-warning d-grid gap-2 d-md-block text-dark fs-4"%>
              </div><!-- /.col-lg-4 -->
            <%end%>
          </div>
        </div>
    </div>    
  </div>
</div>

<%#= link_to 'New Software', new_software_path %>

app/views/softwares/new.html.erb
<h1>New Software</h1>

<%= render 'form', software: @software %>

<%= link_to 'Back', softwares_path %>

app/views/softwares/show.html.erb
<hr class="featurette-divider mx-5 text-light">
<div class="container-fluid">
  <div class="row text-center px-3 align-items-center">
    <div class="col-12 ">
      <%= link_to ('<i class="fa fa-arrow-left"></i>').html_safe, softwares_path, class:"mx-5 text-warning fs-1 align-items-start "%>
    </div>
  </div>
</div>
<hr class="featurette-divider mx-5 text-light">

<div class="container-fluid">
  <div class="row text-center px-3 align-items-center d-flex justify-content-center">
    <div class="col-8 ">
      <h1 class="text-warning">Centered hero</h1>
      <hr class="featurette-divider mx-5 text-dark">
      <p class="lead text-white">Quickly design and customize responsive mobile-first sites with Bootstrap, the world’s most popular front-end open source toolkit, featuring Sass variables and mixins, responsive grid system, extensive prebuilt components, and powerful JavaScript plugins.</p>
    </div>    
  </div>
</div>

<div class="container my-5 bg-dark">
    <div class="row p-4 pb-0 pe-lg-0 pt-lg-5 align-items-center rounded-3 border shadow-lg">
        <div class="col-lg-7 p-3 p-lg-5 pt-lg-3">
          <h1 class="display-4 fw-bold lh-1 text-warning"><%= @software.name %></h1>
          <p class="lead text-white"><%= @software.about %></p>
        </div>
        <div class="col-lg-4 offset-lg-1 p-0 oprojectow-hidden ">
            <%= image_tag @software&.image_url,alt: "image", class:"bd-placeholder-img", style: "width: 80%;" %>
        </div>
    </div>
</div>   